---
# hedgedoc itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc
  namespace: hedgedoc
  labels:
    app: hedgedoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      containers:
      - name: hd
        image: quay.io/hedgedoc/hedgedoc:1.9.0
        ports:
          - containerPort: 3000
        env:
          # values from https://docs.hedgedoc.org/configuration/
          - {name: NODE_ENV, value: "production"}
          - {name: CMD_DOMAIN, value: "hd-test.k8s-test.cs.aalto.fi"}
          - {name: CMD_URL_ADDPORT, value: "false"}
          - {name: CMD_DB_URL, value: "postgres://hedgedoc:password@hd-db-svc:5432/hedgedoc"}
          - {name: CMD_DOMAIN, value: "localhost"}
          - {name: CMD_URL_ADDPORT, value: "true"}
          - {name: CMD_LOGLEVEL, value: "debug"}
          # Create with:     kubectl create -n hedgedoc secret generic session-secret --from-literal=secret=SECRET-VALUE-HERE
          - {name: CMD_SESSION_SECRET, valueFrom: {secretKeyRef: {name: session-secret, key: secret }}}
        #volumeMounts:
        #  - mountPath: /hedgedoc/public/uploads
        #    name: hd-uploads
