---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hd-db
  namespace: hedgedoc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #volumeName: hd-db
  accessModes: [ReadWriteOnce]
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hd-uploads
  namespace: hedgedoc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #volumeName: hd-uploads
  accessModes: [ReadWriteMany]
  capacity:
    storage: 1Gi
