---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-db
  namespace: hedgedoc
spec:
  storageClassName: nfs-client # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
#---
